name: 'export-env-action'
description: 'Exports .env file variables to job env'
author: 'cardinalby'
inputs:
  envFile:
    description: 'Path to .env file or Path to multiple .env files concatenated by `|`'
    required: true
  filter:
    description: 'Filter regexp to only export specific variables matching the filter'
    required: false
  expand:
    description: 'Substitute ${VAR} references by values of correspondent vars'
    required: false
    default: 'false'
  expandWithJobEnv:
    description: 'Use step env for expanding ${VAR} references'
    required: false
    default: 'false'
  export:
    description: |
      Export variables to a job environment. If `false`, all variables will be set as an action 
      outputs instead.
    required: false
    default: 'true'
  mask:
    description: 'Mask all result values (after expanding) as secrets'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
